### ISSUE TITLE
Show useful errors/warnings for small profiles

### ISSUE THREAD

**Issue by edsiper** [plasma-umass/coz#46] opened 2016-04-03 22:56 UTC
I am trying the benchmark tests and uploading the profile.coz file from _toy/_  it's not working (nothing happens), the file have the following content:

```
startup time=1459720345913594695
runtime time=3898923478
samples location=/home/edsiper/coding/coz/benchmarks/toy/toy.cpp:9  count=3854
samples location=/home/edsiper/coding/coz/benchmarks/toy/toy.cpp:13 count=3592
startup time=1459723393567704308
runtime time=3673730614
samples location=/home/edsiper/coding/coz/benchmarks/toy/toy.cpp:9  count=3668
samples location=/home/edsiper/coding/coz/benchmarks/toy/toy.cpp:13 count=3497
```

any advice is appreciated.

**Comment by ccurtsinger** [comment] 2016-04-04 14:37
The `toy` program doesn't have any progress points because it is meant to be run in the `--end-to-end` mode. Your profile doesn't have any experiments in it, so I'm guessing you didn't pass this flag to `coz run`. If you add that and collect quite a few more runs (at least 50) then the profile should work.

**Comment by edsiper** [comment] 2016-04-04 19:34
thanks that fixed the problem.

Side question, for a program that runs in an event loop in a single thread, is Coz suitable to perform performance suggestions based on fixed routines ?

**Comment by ccurtsinger** [comment] 2016-04-06 19:16
Coz will certainly produce useful information for a program with an event loop, but it is roughly equivalent to what a conventional profiler would give you. If you put a progress point at the end of the event loop, the potential impact of speeding up each of the tasks in the event loop is just proportional to the time spent running that task.

**Comment by ccurtsinger** [comment] 2016-04-06 19:20
I'm updating the issue and leaving it open because the coz plot interface should give useful feedback when a profile is empty or too small to plot.

**Comment by petterreinholdtsen** [comment] 2016-08-08 22:51
Having more useful feedback for "small profiles" would have saved me a few hours of trying to figure out why I did not get any graphs or anything when uploading the profile I got. :)

**Comment by ccurtsinger** [comment] 2019-08-18 17:02
This was fixed a while back, but never made it into the `gh-pages` branch.
Duplicate of #25.

**Closed by ccurtsinger** 2019-08-18 17:02 UTC
Labels: bug, ready
