### ISSUE TITLE
Switch build to CMake

### ISSUE THREAD

**Issue by klimkin** [plasma-umass/coz#172] opened 2020-10-28 18:47 UTC
Using CMake will make it easier to build the tool on variety of systems. You can find a working `CMakeLists.txt` file in this PR for Conan Center Index: https://github.com/conan-io/conan-center-index/pull/3282

**Comment by bjorn3** [comment] 2020-10-28 18:49
Duplicate of #170

**Closed** 2020-10-28 18:50 UTC
